" Load defaults.vim as explained here:
" https://github.com/vim/vim/blob/v8.0.0885/runtime/doc/starting.txt#L1038
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" Fix scroll down problem in Suckless terminal (st) as explained here:
" https://www.reddit.com/r/linux4noobs/comments/aa5yot/suckless_simple_terminal_cant_scroll_down_in_vim/
set ttymouse=sgr

" Store all temp files (.swo and .swp) in ~/.vim/tmp
" http://vimdoc.sourceforge.net/htmldoc/options.html#'dir'
set dir=$HOME/.vim/tmp

" Set width of foldcolumn to 1.
" http://vimdoc.sourceforge.net/htmldoc/options.html#'foldcolumn'
set foldcolumn=1

" Add line numbers.
" http://vimdoc.sourceforge.net/htmldoc/options.html#'number'
set number

" Set the width of the tab character to 4 spaces.
" http://vimdoc.sourceforge.net/htmldoc/options.html#'tabstop'
set tabstop=4

" Set number of spaces to use for each step of (auto)indent to 4.
" http://vimdoc.sourceforge.net/htmldoc/options.html#'shiftwidth'
set shiftwidth=4

" Define which characters to use under list mode.
" http://vimdoc.sourceforge.net/htmldoc/options.html#'listchars'
set listchars=tab:├─,trail:·,eol:¬,nbsp:•,precedes:«,extends:»
"set listchars=tab:»\ ,trail:·,eol:¬,nbsp:•,precedes:←,extends:→
"set listchars=tab:∣―,trail:·,eol:¬,nbsp:•,precedes:«,extends:»

" Turn on list mode to display invisible characters.
" http://vimdoc.sourceforge.net/htmldoc/options.html#'list'
set list

" Set the highlight color for "tabs", "nbps", and "trail"
hi SpecialKey ctermfg=DarkGrey

" Show a margin at column 100 and set its color.
" http://vimdoc.sourceforge.net/htmldoc/options.html#'colorcolumn'
set colorcolumn=100
highlight ColorColumn ctermbg=DarkGrey guibg=DarkGrey

" Treat LESS and SASS files as CSS files
au BufRead,BufNewFile *.less set filetype=css
au BufRead,BufNewFile *.scss set filetype=css

" Use 2 spaces for indentation in YAML files (source: https://stackoverflow.com/a/54747794).
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab indentkeys-=0# indentkeys-=<:>