#!/usr/bin/env sh

# This alias is used to manage the dotfiles repository instead of using git directly.
alias dotfiles="/usr/bin/git --git-dir=\"$HOME/.files/.git/\" --work-tree=\"$HOME\" -c status.showUntrackedFiles=no"

# Set default flags for ls and add a few helpful aliases.
alias ls="ls -F --group-directories-first --color=always"
alias ll="ls -alh"
alias la="ls -Ah"
alias l="ls -C"

# Set default flags for grep, egrep, and fgrep.
alias grep="grep --color=always"
alias egrep="egrep --color=always"
alias fgrep="fgrep --color=always"

# Start the SSH agent when startx is executed.
# https://wiki.archlinux.org/index.php/SSH_keys#ssh-agent_as_a_wrapper_program
alias startx="ssh-agent startx"

# Source private aliases from ~/.files/private/aliases if the file exists.
if [[ -r "$HOME/.files/private/aliases" ]]; then
	source "$HOME/.files/private/aliases"
fi