#!/usr/bin/env sh

# Make vim the default editor.
export EDITOR="vim"

# Add ~/.local/bin to $PATH if it exists.
if [[ -d "$HOME/.local/bin" ]]; then
	export PATH="$PATH:$HOME/.local/bin"
fi

# Add ~/.files/bin to $PATH
export PATH="$PATH:$HOME/.files/bin"

# Load nvm if it's installed: https://github.com/nvm-sh/nvm#manual-install
if [[ -d "$HOME/.nvm" ]]; then
	export NVM_DIR="$HOME/.nvm"
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
	[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi

# Source private exports from ~/.private/exports if the file exists.
if [[ -r "$HOME/.private/exports" ]]; then
	source "$HOME/.private/exports"
fi

# vim: filetype=sh