#!/usr/bin/env sh

# Make vim the default editor.
export EDITOR="vim"

# Add ~/.local/bin and ~/.files/bin to $PATH
export PATH="$PATH:$HOME/.local/bin:$HOME/.files/bin"

# Path to private dotfiles.
PRIVATE="$HOME/.files/private"

# Add private bin directory to $PATH if it exist.
if [[ -d "$PRIVATE/bin" ]]; then
	export PATH="$PATH:$PRIVATE/bin"
fi

# Load nvm if it's installed: https://github.com/nvm-sh/nvm#manual-install
if [[ -d "$HOME/.nvm" ]]; then
	export NVM_DIR="$HOME/.nvm"
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
	[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi

# Source private exports from ~/.files/private/exports if the file exists.
if [[ -r "$PRIVATE/exports" ]]; then
	source "$PRIVATE/exports"
fi